#!/bin/bash
#SBATCH --partition=general-compute
#SBATCH --qos=general-compute
#SBATCH --cluster=ub-hpc
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=12
#SBATCH --job-name="hhot3f"
#SBATCH --array=0-3
#SBATCH --output="hhot3-%A_%a.out"
#SBATCH --error="hhot3-%A_%a.err"
#SBATCH --mail-user=lyang25@buffalo.edu
#SBATCH --mail-type=END
#SBATCH --requeue

tic=`date +%s`
echo "Start Time = "`date`

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR
module use /projects/academic/yijunsun/leyang/modulefiles
module load python/anaconda3
module list
ulimit -s unlimited

VALUES=({0..3})
python survey_step3.py ${VALUES[$SLURM_ARRAY_TASK_ID]}

echo "All Done!"

echo "End Time = "`date`
toc=`date +%s`

elapsedTime=`expr $toc - $tic`
echo "Elapsed Time = $elapsedTime seconds"
