#!/bin/bash
#SBATCH --partition=general-compute
#SBATCH --qos=general-compute
#SBATCH --cluster=ub-hpc
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --tasks-per-node=12
#SBATCH --mail-user=lyang25@buffalo.edu
#SBATCH --mail-type=END
#SBATCH --output="fdrnet-%A_%a.out"
#SBATCH --error="fdrnet-%A_%a.err"
#SBATCH --job-name="fdrnet"
#SBATCH --array=0-879
#SBATCH --requeue

tic=`date +%s`
echo "Start Time = "`date`

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR
module load cplex/12.7
module use /projects/academic/yijunsun/leyang/modulefiles
module load python/anaconda2
module list
ulimit -s unlimited

export PYTHONPATH=/util/academic/cplex/12.7/cplex/python/2.7/x86-64_linux:$PYTHONPATH
VALUES=({0..879})
python runSimulation2020_conductance_biogrid.py ${VALUES[$SLURM_ARRAY_TASK_ID]}

echo "All Done!"

echo "End Time = "`date`
toc=`date +%s`

elapsedTime=`expr $toc - $tic`
echo "Elapsed Time = $elapsedTime seconds"

