#!/bin/bash
#SBATCH --partition=general-compute
#SBATCH --qos=general-compute
#SBATCH --cluster=ub-hpc
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=12
#SBATCH --job-name="domino1"
#SBATCH --output="domino1.out"
#SBATCH --error="domino1.err"
#SBATCH --mail-user=lyang25@buffalo.edu
#SBATCH --mail-type=END

tic=`date +%s`
echo "Start Time = "`date`

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR
module use /projects/academic/yijunsun/leyang/modulefiles
module load python/anaconda3
source activate domino-env
module list
ulimit -s unlimited

slicer --network_file network/biogrid_edge_list.sif --output_file network/biogrid_slices.txt
slicer --network_file network/irefindex18_edge_list.sif --output_file network/irefindex18_slices.txt
slicer --network_file network/reactome21_edge_list.sif --output_file network/reactome21_slices.txt
slicer --network_file network/string_edge_list.sif --output_file network/string_slices.txt

echo "All Done!"

echo "End Time = "`date`
toc=`date +%s`

elapsedTime=`expr $toc - $tic`
echo "Elapsed Time = $elapsedTime seconds"
