#!/bin/bash
#SBATCH --partition=general-compute
#SBATCH --qos=general-compute
#SBATCH --cluster=ub-hpc
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=12
#SBATCH --job-name="bionet"
#SBATCH --array=0-999
#SBATCH --output="bionet-%A_%a.out"
#SBATCH --error="bionet-%A_%a.err"
#SBATCH --mail-user=lyang25@buffalo.edu
#SBATCH --mail-type=END
#SBATCH --requeue
tic=`date +%s`
echo "Start Time = "`date`

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR
module load r
module list
ulimit -s unlimited
VALUES=({1..1000})
Rscript bionet.R ${VALUES[$SLURM_ARRAY_TASK_ID]}

echo "All Done!"

echo "End Time = "`date`
toc=`date +%s`

elapsedTime=`expr $toc - $tic`
echo "Elapsed Time = $elapsedTime seconds"
