#!/bin/bash
#SBATCH --partition=general-compute
#SBATCH --qos=general-compute
#SBATCH --cluster=ub-hpc
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=12
#SBATCH --job-name="netcore"
#SBATCH --array=0-879
#SBATCH --output="netcore-%A_%a.out"
#SBATCH --error="netcore-%A_%a.err"
#SBATCH --mail-user=lyang25@buffalo.edu
#SBATCH --mail-type=END
#SBATCH --requeue
#SBATCH --mem=100G
tic=`date +%s`
echo "Start Time = "`date`

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR
module use /projects/academic/yijunsun/leyang/modulefiles
module load python/anaconda3
source activate netcore
module list
ulimit -s unlimited

VALUES=({0..879})
python run_netcore.py  ${VALUES[$SLURM_ARRAY_TASK_ID]}

echo "All Done!"

echo "End Time = "`date`
toc=`date +%s`

elapsedTime=`expr $toc - $tic`
echo "Elapsed Time = $elapsedTime seconds"
